### ISSUE TITLE
ValueError during lyrics download

### ISSUE THREAD

**Issue by Vuizur** [SekouD/lyricsmaster#206]
* LyricsMaster version: 2.7.18
* Python version: 3.6
* Operating System: Windows 10

### Description
I tried to download some lyrics like in the tutorial but got an error.

### What I Did

```
from lyricsmaster import LyricWiki

provider = LyricWiki()
discography = provider.get_lyrics('Manowar')
```
The traceback:
```
Traceback (most recent call last):
  File "C:\Users\MyName\PycharmProjects\songtext\songtext.py", line 5, in <module>
    discography = provider.get_lyrics('Manowar')
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\lyricsmaster\providers.py", line 172, in get_lyrics
    album_title, release_date = self.get_album_infos(elmt)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python36-32\lib\site-packages\lyricsmaster\providers.py", line 378, in get_album_infos
    i = tag.text.index(' (')
ValueError: substring not found
```

**Comment by SekouD** [comment]
Hi, thanks for submitting this bug report.

I will try to reproduce and keep I will keep in touch with you ASAP.

Cheers.

**Comment by SekouD** [comment]
Hi @Vuizur.
Thanks for providing such a useful and detailed bug report 👍 .
I was able to reproduce your bug and correct the bug quickly thanks to the quality of your report.

I just updated the code on the repository, and I will shortly build and push the updated package on [PYPI](https://pypi.org/project/lyricsmaster/) (the new version will be 2.7.19).

Thanks again and have a nice evening.

SekouD.
