### ISSUE TITLE
Duplicating output

### ISSUE THREAD

**Issue by estribiyo** [SekouD/lyricsmaster#215]
* LyricsMaster version: 2.7.24
* Python version: 3.5.3
* Operating System: Debian 9

### Description

As I use lyricsmaster as a library, assigning a handler on it, it causes a duplicated output.

### What I Did

Creating a new instance for example, it will output the following two lines (the first with the handler of lyricsmaster, the other one on the caller).

```
Anonymous requests disabled. The connexion will not be anonymous.
22-03 12:58    INFO   providers.py   74: Anonymous requests disabled. The connexion will not be anonymous.
```

Maybe, using ```logging.basicConfig``` instead of adding a new handler it resolves as you expect and prevents the other behaviour...

```
    level = 'WARNING'
    fmt='\r%(asctime)s%(levelname)8s%(filename)15s %(lineno)4s: %(message)s'
    logging.basicConfig(format=fmt, level=level)
```

**Comment by SekouD** [comment]
Hi @estribiyo, thanks for submitting this issue and for using lyricsmaster.
I integrated the changes you proposed to the logger configuration and merged the changes to master.

Can you try out the change and let me know if this resolves your issue of duplication?

Cheers!

**Comment by estribiyo** [comment]
Perfect!

```
23-03 17:05   ERROR      spider.py  153: object of type 'NoneType' has no len()
23-03 17:05    INFO   providers.py   74: Anonymous requests disabled. The connexion will not be anonymous.
23-03 17:05    INFO   providers.py   74: Anonymous requests disabled. The connexion will not be anonymous.
23-03 17:05    INFO   providers.py   74: Anonymous requests disabled. The connexion will not be anonymous.
23-03 17:05    INFO   providers.py  310: Downloading Trigeneración [Remastered]
23-03 17:05    INFO   providers.py  320: Skipped downloading Trigeneración [Remastered] as no lyrics matched.
23-03 17:05    INFO   providers.py  310: Downloading Trigeneración (Remastered)
23-03 17:05    INFO   providers.py  320: Skipped downloading Trigeneración (Remastered) as no lyrics matched.
23-03 17:05    INFO   providers.py  310: Downloading Trigeneración 1
23-03 17:05    INFO   providers.py  320: Skipped downloading Trigeneración 1 as no lyrics matched.
23-03 17:05    INFO     audiodb.py 1092: []
```

**Comment by SekouD** [comment]
Great!

I am glad this solved your issue.

Thanks for your contribution @estribiyo.

I credited you in lyricsmaster's documentation for your help enhancing the handling of accented and special characters as well as your contribution for the logger.

Cheers.
